%% Die aktuellen Links und Dateinamen für den JVK:

%% Basic:
\def\kurs{Java Vorkurs}
\def\semester{2023}	%TODO: Rausnehmen (?)
\def\simulator{Matrix-Simulator}

%% Links:
\def\fiusjvk{https://fius.de/index.php/studien-interessierte/java-vorkurs/}
\def\jdkTutorial{https://youtu.be/rGeOtJHodtY}
\def\eclipseTutorial{https://youtu.be/zxH3G1MTrVs}
\def\jvkpackage{Release 1.0.1}
\def\javadocRoot{https://fius.github.io/ICGE2/master/}
\def\jvkpackageurl{https://github.com/FIUS/jvk/releases/latest}


%% Java:
\def\jvkpackage{JVK.Source.Code.zip}
\def\javaPackageName{de.unistuttgart.informatik.fius.jvk}
\newcommand\ownclass{\lstinline|MyNeo|}
\newcommand\superclass{\lstinline|Neo|}