%% Die aktuellen Links und Dateinamen für den JVK:

%% Basic:
\def\kurs{Java Vorkurs}
\def\semester{2022}	%TODO: Rausnehmen (?)
\def\simulator{Matrix-Simulator}

%% Links:
\def\eclipseTutorial{https://youtu.be/zxH3G1MTrVs}
\def\javadocRoot{https://fius.github.io/ICGE2/master/}
\def\jvkpackageurl{https://fius.de/wp-content/uploads/2020/10/JavaVorkurs2020\_EclipseProjekt.zip}	% TODO: change URL

%% Java:
\def\jvkpackage{JavaVorkurs\_EclipseProjekt.zip}
\def\javaPackageName{de.unistuttgart.informatik.fius.jvk}