name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd sheets ; make
      - uses: actions/upload-artifact@v2
        with:
          name: sheet-pdfs
          path: sheets/*/jvk-blatt*.pdf
